# Generated by Django 4.2.10 on 2024-02-22 14:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('secret_code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=80)),
                ('text', models.CharField(blank=True, max_length=200)),
                ('payment_method', models.CharField(choices=[('STRIPE', 'Stripe'), ('INVOICE', 'Invoice')], default='STRIPE', max_length=15)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('FINISHED', 'Finished')], default='WAITING', max_length=15)),
                ('payment_status', models.CharField(choices=[('WAITING', 'Waiting'), ('FINISHED', 'Finished')], default='WAITING', max_length=15)),
                ('option_hackaton', models.BooleanField()),
                ('option_tshirt', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.application')),
            ],
        ),
    ]
