# Generated by Django 5.0.2 on 2024-03-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllowedEmail',
        ),
        migrations.AlterField(
            model_name='eventoption',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
