# Generated by Django 4.2.10 on 2024-02-27 18:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('secret_code', models.UUIDField(default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=80)),
                ('text', models.CharField(blank=True, max_length=200)),
                ('payment_method', models.CharField(choices=[('STRIPE', 'Stripe'), ('INVOICE', 'Invoice')], default='STRIPE', max_length=15)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('FINISHED', 'Finished')], default='WAITING', max_length=15)),
                ('payment_status', models.CharField(choices=[('WAITING', 'Waiting'), ('FINISHED', 'Finished')], default='WAITING', max_length=15)),
                ('option_hackaton', models.BooleanField(default=False)),
                ('option_tshirt', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='application',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
