# Generated by Django 5.0.2 on 2024-03-01 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_allowedemail_alter_eventoption_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='text',
            new_name='comment',
        ),
    ]
