# Generated by Django 5.0.2 on 2024-02-29 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_allowedemails_allowedemail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allowedemail',
            old_name='allow_apply',
            new_name='allow_participation',
        ),
        migrations.RenameField(
            model_name='allowedemail',
            old_name='omit_payment',
            new_name='free_participation',
        ),
    ]
