# Generated by Django 5.0.2 on 2024-03-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_sitepreferences_allow_only_listed_emails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='payment_status',
            field=models.CharField(
                choices=[
                    ('WAITING',
                     'Waiting'),
                    ('OK',
                     'Ok')],
                default='WAITING',
                max_length=15),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(
                choices=[
                    ('WAITING',
                     'Waiting for activation'),
                    ('PAYMENT',
                     'Waiting for payment'),
                    ('ACTIVE',
                     'Active'),
                    ('CLOSED',
                     'Closed')],
                default='WAITING',
                max_length=15),
        ),
    ]
