# Generated by Django 5.0.2 on 2024-02-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_allow_apply_allowedemail_allow_participation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allowedemail',
            name='id',
        ),
        migrations.AlterField(
            model_name='allowedemail',
            name='email',
            field=models.EmailField(max_length=80, primary_key=True, serialize=False),
        ),
    ]
