# Generated by Django 5.0.2 on 2024-02-29 13:33

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_allowedemail_id_alter_allowedemail_email'),
        # ('preferences', '0002_auto_20181220_0803'),
        ('preferences', '0003_alter_preferences_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePreferences',
            fields=[
                ('preferences_ptr',
                 models.OneToOneField(
                     auto_created=True,
                     on_delete=django.db.models.deletion.CASCADE,
                     parent_link=True,
                     primary_key=True,
                     serialize=False,
                     to='preferences.preferences')),
                ('portal_contact_email',
                 models.EmailField(
                     max_length=80)),
            ],
            bases=(
                'preferences.preferences',
            ),
            managers=[
                ('singleton',
                 django.db.models.manager.Manager()),
            ],
        ),
    ]
