# Generated by Django 5.0.2 on 2024-02-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_sitepreferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitepreferences',
            name='portal_contact_email',
        ),
        migrations.AddField(
            model_name='sitepreferences',
            name='allow_only_listed_emails',
            field=models.BooleanField(default=False),
        ),
    ]
