# Generated by Django 5.0.2 on 2024-02-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_sitepreferences_portal_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='site_title',
            field=models.CharField(default='DDS Invoicing', max_length=80),
        ),
    ]
